name: build
on: [push, workflow_dispatch]
jobs:
  apk:
    runs-on: ubuntu-latest
    env:
      OEFFI_NG_JKS_PASSWORD: dummy
    steps:
      - uses: actions/checkout@v4
        with: { submodules: recursive }
      - run: git checkout -B nextgen
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '21' }
      - uses: android-actions/setup-android@v3
      - name: use debug keystore
        run: sed -i 's/signingConfig = signingConfigs.oeffi_ng/signingConfig = signingConfigs.debug/' androidstudio/oeffi-studio/build.gradle
      - run: chmod +x androidstudio/gradlew
      - run: ./gradlew :oeffi-studio:assembleNgDebug
        working-directory: androidstudio
      - uses: actions/upload-artifact@v4
        with:
          name: oeffi-ng-debug
          path: androidstudio/oeffi-studio/build/outputs/apk/**/*.apk

